<!-- Top Title Ribbon Starts -->
<table cellSpacing="0" cellPadding="0" width="100%" border="0">		
<!-- Title Ribbon Top Starts -->
	<tr>
		<td bgColor="#ffffff"  height="2"></td>
	</tr>
	<tr>
		<td bgColor="#ff9900"  height="3"></td>
	</tr>
	<tr>
		<td bgColor="#ffffff"  height="2"></td>
	</tr>
	<!-- Title Ribbon Top Ends -->
	<!-- Title Bar Starts -->
	<tr>
		<td bgColor="green">
			<TABLE cellSpacing="2" cellPadding="2" width="100%" border="0" ID="Table2">
				<colgroup bgColor="#0e9c0e">
					<col width="50">
					<col width="70">
					<col>
				</colgroup>
				<TR>
					<td vAlign="middle"><A class="navtitlebar" href="Default.aspx"><B>&nbsp;Home</B></A></td>
					<td vAlign="middle"><A class="navtitlebar" href="Default.aspx"><B>&nbsp;Reports</B></A></td>
					<td vAlign="middle">
						<A class="navtitlebar" href="Rectifications.aspx">
							<B>&nbsp;Rectifications</B>
						</A>
					</td>
					<TD class="navtitlebar" bgColor="green">&nbsp;</TD>
				</TR>
			</TABLE>
		</td>
	</tr>
	<!-- Title Bar Ends -->
	<!-- Title Ribbon Bottom Starts -->
	<tr>
		<td bgColor="#ffffff" height="2"></td>
	</tr>
	<tr>
		<td bgColor="#cccccc" height="3"></td>
	</tr>
	<tr>
		<td bgColor="#ffffff"  height="2"></td>
	</tr>
	<!-- Title Ribbon Bottom Ends -->
</table>
<!-- Top Title Ribbon Ends -->


