//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdHocInspection_notice
    {
        public int Notice_ID { get; set; }
        public System.Guid AdHoc_Schedule_PKUID { get; set; }
        public bool AdHocInspection_notice_Email_Sent { get; set; }
        public System.DateTime AdHocInspectionNotice_DateAdded { get; set; }
    }
}
