//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calculation_element_attribute
    {
        public int data_entry_form_id { get; set; }
        public int element_id { get; set; }
        public int element_type_id { get; set; }
        public string calc_expression { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
        public string evaluate_math_expression { get; set; }
    }
}
