//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calculation_query
    {
        public int calculation_query_id { get; set; }
        public string calculation_query_name { get; set; }
        public string calculation_query_desc { get; set; }
        public Nullable<int> calculation_query_function_id { get; set; }
        public Nullable<int> calculation_query_join_id { get; set; }
        public Nullable<int> calculation_query_criteria_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
