//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes_and_Priorities_WM
    {
        public string Class { get; set; }
        public string Zone { get; set; }
        public string Std_or_Deep { get; set; }
        public float Priority_Weighting { get; set; }
        public int A_Value { get; set; }
        public int B_Value { get; set; }
        public int C_Value { get; set; }
        public int D_Value { get; set; }
    }
}
