//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleanliness_Grades
    {
        public string Grade { get; set; }
        public string Description { get; set; }
        public string Deep_Description { get; set; }
        public System.Guid pkUID { get; set; }
        public System.DateTime last_modified { get; set; }
    }
}
