//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class column_list
    {
        public int column_id { get; set; }
        public int table_id { get; set; }
        public string column_name { get; set; }
        public int column_type_id { get; set; }
        public Nullable<int> column_size { get; set; }
        public Nullable<int> column_dec { get; set; }
        public string nulls { get; set; }
        public Nullable<int> column_index { get; set; }
        public Nullable<int> sort_index { get; set; }
        public Nullable<int> sort_direction_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
