//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conditional_element_attribute
    {
        public int data_entry_form_id { get; set; }
        public int element_id { get; set; }
        public int element_attribute_type_id { get; set; }
        public string element_attribute_value { get; set; }
        public string element_attribute_default { get; set; }
        public Nullable<int> parent_column_id { get; set; }
        public Nullable<int> parent_data_entry_form_id { get; set; }
        public Nullable<int> parent_element_id { get; set; }
        public Nullable<int> parent_element_property_id { get; set; }
        public string parent_element_operator { get; set; }
        public string parent_element_value { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
