//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConMon_report_metadata
    {
        public string conmon_report_category { get; set; }
        public double pct_monitored_weekly { get; set; }
        public double standard_default_notice_pct_threshold { get; set; }
    }
}
