//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_entry_form_filter
    {
        public int data_entry_form_id { get; set; }
        public int parent_data_entry_form_id { get; set; }
        public Nullable<int> parent_filter_element_id { get; set; }
        public Nullable<int> parent_filter_element_type_id { get; set; }
        public Nullable<int> child_filter_element_id { get; set; }
        public Nullable<int> child_filter_element_type_id { get; set; }
        public Nullable<int> filter_column_id { get; set; }
        public Nullable<int> filter_join_id { get; set; }
        public Nullable<int> filter_criteria_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
