//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_entry_form
    {
        public int data_entry_form_id { get; set; }
        public string data_entry_form_name { get; set; }
        public string data_entry_form_desc { get; set; }
        public string data_entry_form_active { get; set; }
        public string data_entry_form_filter_set { get; set; }
        public string data_entry_form_edit_mode { get; set; }
        public string data_entry_form_initial_rec { get; set; }
        public string data_entry_form_export_delim { get; set; }
        public string data_entry_form_visible { get; set; }
        public Nullable<int> output_table_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
