//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class element
    {
        public int data_entry_form_id { get; set; }
        public int element_id { get; set; }
        public int element_type_id { get; set; }
        public Nullable<int> tab_order { get; set; }
        public Nullable<int> output_column_id { get; set; }
        public Nullable<int> lookup_column_id { get; set; }
        public Nullable<int> lookup_criteria_id { get; set; }
        public Nullable<int> lookup_join_id { get; set; }
        public Nullable<int> parent_element_id { get; set; }
        public Nullable<int> parent_element_type_id { get; set; }
        public Nullable<int> join_id { get; set; }
        public Nullable<int> criteria_id { get; set; }
        public int element_x { get; set; }
        public int element_y { get; set; }
        public int element_width { get; set; }
        public int element_height { get; set; }
        public string element_enabled { get; set; }
        public string element_visible { get; set; }
        public string element_locked { get; set; }
        public string element_null { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
