//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class element_attribute
    {
        public int data_entry_form_id { get; set; }
        public int element_id { get; set; }
        public int element_attribute_type_id { get; set; }
        public string element_attribute_operator { get; set; }
        public string element_attribute_value { get; set; }
        public Nullable<int> element_attribute_elem_id { get; set; }
        public string element_attribute_elem_pos { get; set; }
        public Nullable<int> element_attribute_numgrp { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
