//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Contact_Role
    {
        public int Email_Role_ID { get; set; }
        public int Email_Contact_ID { get; set; }
        public bool Email_Contact_Enabled { get; set; }
    
        public virtual Email_Contact Email_Contact { get; set; }
        public virtual Email_Role Email_Role { get; set; }
    }
}
