//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estates_EH1
    {
        public string Estate_location { get; set; }
        public string Estate_name { get; set; }
        public string Street_Name { get; set; }
        public string Limits { get; set; }
    }
}
