//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estates_EH2
    {
        public int ID { get; set; }
        public string Area_name { get; set; }
        public string District_name { get; set; }
        public string Limits { get; set; }
        public string Street_name { get; set; }
        public string Rect_Street_Name { get; set; }
        public string Estate_name { get; set; }
        public string Freq_code { get; set; }
        public Nullable<int> Rcd_Count { get; set; }
    }
}
