//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT
    {
        public int Fact_ID { get; set; }
        public string DIMENSIONS { get; set; }
        public string Fact_Type_Code { get; set; }
        public string Time_Period_Code { get; set; }
        public string Location_Level_Code { get; set; }
        public string Ward_Code { get; set; }
        public Nullable<System.DateTime> Date_Incident_Reported { get; set; }
        public Nullable<System.DateTime> Date_Incident_Inspected { get; set; }
        public Nullable<System.DateTime> Date_Incident_Closed { get; set; }
        public string Outcome { get; set; }
        public string Status { get; set; }
        public Nullable<int> Grid_Reference_Northing { get; set; }
        public Nullable<int> Grid_Reference_Easting { get; set; }
        public Nullable<int> UPRN { get; set; }
        public string Street_Name { get; set; }
        public string Street_Section { get; set; }
        public string Street_Transect { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Customer_Name { get; set; }
        public string FACTS { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<int> Rcd_Count { get; set; }
        public string FACTS4_Abandoned_Vehicles { get; set; }
        public Nullable<System.DateTime> Date_AV_Removed { get; set; }
        public string FACTS4_Street_Cleansing { get; set; }
        public string Cleansing_Type { get; set; }
        public string Detritus_Grade { get; set; }
        public string GPS_Coordinates { get; set; }
        public string Foliage { get; set; }
        public string Fly_Tip_Size { get; set; }
        public string Inspector { get; set; }
        public string Notes { get; set; }
        public string Parked_Cars { get; set; }
        public string Street_Grade { get; set; }
        public string Weather { get; set; }
        public string Weeds { get; set; }
        public string Other_Facts { get; set; }
    
        public virtual Ref_Fact_Types Ref_Fact_Types { get; set; }
        public virtual Ref_Location_Levels Ref_Location_Levels { get; set; }
        public virtual Ref_Time_Periods Ref_Time_Periods { get; set; }
    }
}
