//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grip_user_access_level
    {
        public Nullable<int> access_level_id { get; set; }
        public string access_level_code { get; set; }
        public string access_level_desc { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
