//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grip_user_form
    {
        public Nullable<int> user_id { get; set; }
        public int data_entry_form_id { get; set; }
        public string form_active { get; set; }
        public Nullable<int> access_level_id { get; set; }
        public string regenerate_form { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid pkUID { get; set; }
    }
}
