//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_notice
    {
        public int Notice_ID { get; set; }
        public System.Guid Cleaning_Schedule_PKUID { get; set; }
        public bool Inspection_notice_Email_Sent { get; set; }
    
        public virtual Cleaning_Schedule Cleaning_Schedule { get; set; }
        public virtual Notice Notice { get; set; }
    }
}
