//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectors_and_Wards_ADI
    {
        public string Inspector_Name { get; set; }
        public string Active_YN { get; set; }
        public string Login_Name { get; set; }
        public string Telephone { get; set; }
        public string Ward_Name { get; set; }
    }
}
