//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_database
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ml_database()
        {
            this.ml_ra_agent = new HashSet<ml_ra_agent>();
            this.ml_subscription = new HashSet<ml_subscription>();
        }
    
        public int rid { get; set; }
        public string remote_id { get; set; }
        public System.DateTime script_ldt { get; set; }
        public byte[] seq_id { get; set; }
        public int seq_uploaded { get; set; }
        public string sync_key { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_agent> ml_ra_agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_subscription> ml_subscription { get; set; }
    }
}
