//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_listening
    {
        public string name { get; set; }
        public string device_name { get; set; }
        public string listening { get; set; }
        public string ignore_tracking { get; set; }
        public string source { get; set; }
    
        public virtual ml_device ml_device { get; set; }
    }
}
