//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_model_schema_use
    {
        public int version_id { get; set; }
        public string schema_type { get; set; }
        public string schema_name { get; set; }
        public string table_name { get; set; }
        public string object_name { get; set; }
        public string checksum { get; set; }
    }
}
