//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_primary_server
    {
        public int server_id { get; set; }
        public string name { get; set; }
        public string connection_info { get; set; }
        public byte[] instance_key { get; set; }
        public System.DateTime start_time { get; set; }
    }
}
