//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_passthrough_script
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ml_passthrough_script()
        {
            this.ml_passthrough = new HashSet<ml_passthrough>();
            this.ml_passthrough_repair = new HashSet<ml_passthrough_repair>();
        }
    
        public int script_id { get; set; }
        public string script_name { get; set; }
        public string flags { get; set; }
        public string affected_pubs { get; set; }
        public string script { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_passthrough> ml_passthrough { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_passthrough_repair> ml_passthrough_repair { get; set; }
    }
}
