//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_ra_task_command
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ml_ra_task_command()
        {
            this.ml_ra_task_command_property = new HashSet<ml_ra_task_command_property>();
        }
    
        public long task_id { get; set; }
        public int command_number { get; set; }
        public long flags { get; set; }
        public string action_type { get; set; }
        public string action_parm { get; set; }
    
        public virtual ml_ra_task ml_ra_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_task_command_property> ml_ra_task_command_property { get; set; }
    }
}
