//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_ra_deployed_task
    {
        public long task_instance_id { get; set; }
        public int aid { get; set; }
        public long task_id { get; set; }
        public System.DateTime assignment_time { get; set; }
        public string state { get; set; }
        public long previous_exec_count { get; set; }
        public long previous_error_count { get; set; }
        public long previous_attempt_count { get; set; }
        public long reported_exec_count { get; set; }
        public long reported_error_count { get; set; }
        public long reported_attempt_count { get; set; }
        public System.DateTime last_modified { get; set; }
    
        public virtual ml_ra_agent ml_ra_agent { get; set; }
        public virtual ml_ra_task ml_ra_task { get; set; }
    }
}
