//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_ra_agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ml_ra_agent()
        {
            this.ml_ra_agent_property = new HashSet<ml_ra_agent_property>();
            this.ml_ra_deployed_task = new HashSet<ml_ra_deployed_task>();
            this.ml_ra_managed_remote = new HashSet<ml_ra_managed_remote>();
        }
    
        public int aid { get; set; }
        public string agent_id { get; set; }
        public Nullable<int> taskdb_rid { get; set; }
    
        public virtual ml_database ml_database { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_agent_property> ml_ra_agent_property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_deployed_task> ml_ra_deployed_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_managed_remote> ml_ra_managed_remote { get; set; }
    }
}
