//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_ra_event_staging
    {
        public int taskdb_rid { get; set; }
        public long remote_event_id { get; set; }
        public string event_class { get; set; }
        public string event_type { get; set; }
        public Nullable<long> task_instance_id { get; set; }
        public Nullable<int> command_number { get; set; }
        public Nullable<long> run_number { get; set; }
        public Nullable<int> duration { get; set; }
        public System.DateTime event_time { get; set; }
        public Nullable<long> result_code { get; set; }
        public string result_text { get; set; }
    }
}
