//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_ra_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ml_ra_task()
        {
            this.ml_ra_deployed_task = new HashSet<ml_ra_deployed_task>();
            this.ml_ra_task_command = new HashSet<ml_ra_task_command>();
            this.ml_ra_task_property = new HashSet<ml_ra_task_property>();
        }
    
        public long task_id { get; set; }
        public string task_name { get; set; }
        public string schema_name { get; set; }
        public Nullable<int> max_running_time { get; set; }
        public Nullable<int> max_number_of_attempts { get; set; }
        public Nullable<int> delay_between_attempts { get; set; }
        public long flags { get; set; }
        public string cond { get; set; }
        public string remote_event { get; set; }
        public int random_delay_interval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_deployed_task> ml_ra_deployed_task { get; set; }
        public virtual ml_ra_schema_name ml_ra_schema_name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_task_command> ml_ra_task_command { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_ra_task_property> ml_ra_task_property { get; set; }
    }
}
