//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_sis_sync_state
    {
        public string remote_id { get; set; }
        public string subscription_id { get; set; }
        public string publication_name { get; set; }
        public string user_name { get; set; }
        public System.DateTime last_upload { get; set; }
        public System.DateTime last_download { get; set; }
    }
}
