//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_subscription
    {
        public int rid { get; set; }
        public string subscription_id { get; set; }
        public int user_id { get; set; }
        public decimal progress { get; set; }
        public string publication_name { get; set; }
        public System.DateTime last_upload_time { get; set; }
        public System.DateTime last_download_time { get; set; }
    
        public virtual ml_database ml_database { get; set; }
        public virtual ml_user ml_user { get; set; }
    }
}
