//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_table_scripts
    {
        public string version { get; set; }
        public string @event { get; set; }
        public string table_name { get; set; }
        public string script_language { get; set; }
        public string script { get; set; }
    }
}
