//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ml_user()
        {
            this.ml_subscription = new HashSet<ml_subscription>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public byte[] hashed_password { get; set; }
        public Nullable<int> policy_id { get; set; }
        public string user_dn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml_subscription> ml_subscription { get; set; }
        public virtual ml_user_auth_policy ml_user_auth_policy { get; set; }
    }
}
