//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice_Service
    {
        public int Notice_Service_ID { get; set; }
        public System.DateTime Notice_Service_Last_Runtime { get; set; }
        public string Notice_Service_Run_Status { get; set; }
        public string Notice_Service_Message { get; set; }
        public bool Notice_Service_Email_Sent { get; set; }
    }
}
