//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice_Frequency_Link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notice_Frequency_Link()
        {
            this.Notices = new HashSet<Notice>();
        }
    
        public int Notice_Frequency_Link_ID { get; set; }
        public int Notice_Type_ID { get; set; }
        public string Freq_Code { get; set; }
        public string Reason_Code { get; set; }
        public int Notice_text_ID { get; set; }
    
        public virtual Notice_text Notice_text { get; set; }
        public virtual Notice_type Notice_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notice> Notices { get; set; }
    }
}
