//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notice()
        {
            this.Inspection_notice = new HashSet<Inspection_notice>();
        }
    
        public int Notice_ID { get; set; }
        public string Notice_reference { get; set; }
        public System.DateTime Notice_served { get; set; }
        public int Notice_Frequency_Link_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection_notice> Inspection_notice { get; set; }
        public virtual Notice_Frequency_Link Notice_Frequency_Link { get; set; }
    }
}
