//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Feedback
    {
        public decimal Feedback_ID { get; set; }
        public decimal User_ID { get; set; }
        public System.DateTime Datetime_of_Feedback { get; set; }
        public string Response_Required_YN { get; set; }
        public string Topic_Code { get; set; }
        public string Topic_Other { get; set; }
        public string Level_of_Satisfaction_Code { get; set; }
        public string Comment_Text { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> Datetime_of_Response { get; set; }
        public string Feedback_Status_Code { get; set; }
    
        public virtual Public_Users Public_Users { get; set; }
        public virtual Ref_Feedback_Status Ref_Feedback_Status { get; set; }
        public virtual Ref_Levels_of_Satisfaction Ref_Levels_of_Satisfaction { get; set; }
        public virtual Ref_Topics Ref_Topics { get; set; }
    }
}
