//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Streets
    {
        public System.Guid pkUID { get; set; }
        public string Street_Name { get; set; }
        public string Limits { get; set; }
        public string Ward_Name { get; set; }
        public string District { get; set; }
        public string Freq_Code { get; set; }
        public string Zone_Nr { get; set; }
        public Nullable<float> length { get; set; }
        public Nullable<System.DateTime> Next_Cleanse_Date { get; set; }
        public System.DateTime last_modified { get; set; }
    }
}
