//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemovedData218
    {
        public int Id { get; set; }
        public Nullable<int> WardCntRemoved24 { get; set; }
        public Nullable<int> WardCntRemovedOver24 { get; set; }
        public string WardName { get; set; }
    }
}
