//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_2_Time_Periods
    {
        public string Month { get; set; }
        public int Year_Nr { get; set; }
        public int Month_Nr { get; set; }
        public int Week_in_Year { get; set; }
        public int Week_in_Month { get; set; }
        public string Day_From { get; set; }
        public string Day_To { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
    }
}
