//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_2_Time_Period_Headers
    {
        public int Year_Nr { get; set; }
        public int Month_Nr { get; set; }
        public int WeekNr1 { get; set; }
        public int WeekNr2 { get; set; }
        public int WeekNr3 { get; set; }
        public int WeekNr4 { get; set; }
        public int WeekNr5 { get; set; }
    }
}
