//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCTrafficLightParm
    {
        public string user_name { get; set; }
        public string comments { get; set; }
        public Nullable<int> grd_a_pct_min { get; set; }
        public Nullable<int> grd_a_pct_max { get; set; }
        public Nullable<int> grd_b_pct_min { get; set; }
        public Nullable<int> grd_b_pct_max { get; set; }
        public Nullable<int> grd_c_pct_min { get; set; }
        public Nullable<int> grd_c_pct_max { get; set; }
        public Nullable<int> grd_d_pct_min { get; set; }
        public Nullable<int> grd_d_pct_max { get; set; }
        public Nullable<int> grd_cd_pct_min { get; set; }
        public Nullable<int> grd_cd_pct_max { get; set; }
    }
}
