//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmplReportSelection
    {
        public int SmplReportSelection_id { get; set; }
        public string SmplReportSelection_code { get; set; }
        public int SmplReportSelection_role_id { get; set; }
        public string SmplReportSelection_name { get; set; }
    
        public virtual grip_role grip_role { get; set; }
    }
}
