//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Abatement_InitialGradesAndRectificationGrades_WM
    {
        public string Cleaning_ID { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public string InitialGrade { get; set; }
        public Nullable<System.DateTime> RectificationDate { get; set; }
        public string RectificationGrade { get; set; }
        public string Zone_Nr { get; set; }
        public string Freq_code { get; set; }
        public string std_or_deep { get; set; }
    }
}
