//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RectifiedOriginalInstructionsDrillDown
    {
        public string Ward_Name { get; set; }
        public string street_name { get; set; }
        public string limits { get; set; }
        public Nullable<System.DateTime> sched_cleaning_date { get; set; }
        public Nullable<System.DateTime> inspected_date { get; set; }
        public string grade { get; set; }
        public string ID { get; set; }
        public System.Guid pkuid { get; set; }
        public string IsRectification { get; set; }
        public Nullable<System.Guid> RectificationPKUID { get; set; }
        public string HasPhoto { get; set; }
    }
}
