//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RectifiedOriginalInstructions
    {
        public string csInspect_Cleaning_ID { get; set; }
        public string csWard_Name { get; set; }
        public string csInspect_Street_Name { get; set; }
        public Nullable<System.DateTime> csInspect_Scheduled_Cleaning_Date { get; set; }
        public string csInspect_Grade { get; set; }
        public System.Guid csInspect_pkUID { get; set; }
        public Nullable<System.Guid> csRect_pkUID { get; set; }
        public Nullable<System.Guid> csOrig_pkUID { get; set; }
        public string csIsRect { get; set; }
    }
}
