//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPL46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zones_and_Classes_WM
    {
        public Nullable<int> Display_Seq { get; set; }
        public string Class { get; set; }
        public string Zone_Nr { get; set; }
        public string Freq_Code { get; set; }
        public string Std_or_Deep { get; set; }
        public string Cleaning_Day { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Rectification_Period { get; set; }
        public int Transect_Frequency_ID { get; set; }
        public System.Guid pkUID { get; set; }
        public System.DateTime last_modified { get; set; }
    
        public virtual Transect_Frequency Transect_Frequency { get; set; }
    }
}
